CREATE TABLE CLICKHOUSE_DATABASE.test1
(
    test UInt8
)
ENGINE = TinyLog();

CREATE TABLE CLICKHOUSE_DATABASE.test2
(
    test UInt8
)
ENGINE = TinyLog();

CREATE TABLE CLICKHOUSE_DATABASE.test3
(
    test UInt8
)
ENGINE = TinyLog();

CREATE TABLE CLICKHOUSE_DATABASE.test4
(
    test UInt8
)
ENGINE = TinyLog();

CREATE TABLE CLICKHOUSE_DATABASE.test5
(
    test UInt8
)
ENGINE = TinyLog();

CREATE TABLE CLICKHOUSE_DATABASE.test6
(
    test UInt8
)
ENGINE = TinyLog();

SHOW TABLES FROM CLICKHOUSE_DATABASE;

SHOW TABLES FROM CLICKHOUSE_DATABASE LIMIT 2;

SHOW TABLES FROM CLICKHOUSE_DATABASE LIMIT 2 * 2;