DROP DATABASE IF EXISTS CLICKHOUSE_DATABASE_1;

CREATE DATABASE CLICKHOUSE_DATABASE_1;

USE CLICKHOUSE_DATABASE_1;

CREATE TABLE t
(
    x UInt8
)
ENGINE = Memory();

SELECT *
FROM merge('', '');

DROP DATABASE CLICKHOUSE_DATABASE_1;