DROP DATABASE IF EXISTS CLICKHOUSE_DATABASE;

DROP DATABASE IF EXISTS CLICKHOUSE_DATABASE_1;

CREATE DATABASE CLICKHOUSE_DATABASE
ENGINE = Replicated('/test/02072/{database}_1', '{shard}', '{replica}_1');

SET distributed_ddl_output_mode = 'none';

CREATE TABLE CLICKHOUSE_DATABASE.`test%_\\_`
(
    n int
)
ENGINE = Log();

SHOW TABLES FROM CLICKHOUSE_DATABASE;

CREATE DATABASE CLICKHOUSE_DATABASE_1
ENGINE = Replicated('/test/02072/{database}', '{shard}', '{replica}_2');

DROP DATABASE CLICKHOUSE_DATABASE;

SYSTEM SYNC DATABASE REPLICA CLICKHOUSE_DATABASE_1;

SHOW TABLES FROM CLICKHOUSE_DATABASE_1;

DROP DATABASE CLICKHOUSE_DATABASE_1;