-- https://github.com/ClickHouse/ClickHouse/issues/61014
SET enable_analyzer = '1';

DROP DATABASE IF EXISTS CLICKHOUSE_DATABASE;

CREATE DATABASE CLICKHOUSE_DATABASE;

CREATE TABLE CLICKHOUSE_DATABASE.a
(
    i int
)
ENGINE = Log();

SELECT CLICKHOUSE_DATABASE.a.i
FROM
    CLICKHOUSE_DATABASE.a,
    CLICKHOUSE_DATABASE.a AS x;