DROP DATABASE IF EXISTS CLICKHOUSE_DATABASE;

CREATE DATABASE IF NOT EXISTS CLICKHOUSE_DATABASE
ENGINE = Memory();

DROP TABLE IF EXISTS CLICKHOUSE_DATABASE.v0;

CREATE MATERIALIZED VIEW CLICKHOUSE_DATABASE.v0
REFRESH AFTER 1 SECOND APPEND
ENGINE = MergeTree()
ORDER BY tuple()
AS
SELECT 1 AS c0;

DETACH TABLE CLICKHOUSE_DATABASE.v0 PERMANENTLY; -- { serverError NOT_IMPLEMENTED }

ALTER TABLE CLICKHOUSE_DATABASE.v0 MODIFY REFRESH AFTER 1 SECOND APPEND;