SET max_block_size = '10';

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.5 WITH TIES;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.9 WITH TIES;

SELECT number
FROM numbers(10)
ORDER BY number ASC
LIMIT 0.1 WITH TIES;

SET max_block_size = '3';

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 5;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.25 WITH TIES
OFFSET 12;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 10;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.9 WITH TIES
OFFSET 5;

SELECT number
FROM numbers(15)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 5;

SELECT number
FROM numbers(14)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 5;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.25 WITH TIES
OFFSET 5;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 15;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.05 WITH TIES
OFFSET 5;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 0.25;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.25 WITH TIES
OFFSET 0.6;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 0.5;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.9 WITH TIES
OFFSET 0.25;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.25 WITH TIES
OFFSET 0.25;

SELECT number
FROM numbers(15)
ORDER BY number ASC
LIMIT 0.5 WITH TIES
OFFSET 0.33;

SELECT number
FROM numbers(20)
ORDER BY number ASC
LIMIT 0.05 WITH TIES
OFFSET 0.25;